extends Node
const Compiler = preload("res://addons/material_maker/particles/modular/compiler.gd")
const Fixtures = preload("fixtures.gd")
const Exporter = preload("res://addons/material_maker/particles/modular/exporter.gd")
const Dialog = preload("res://material_maker/panels/modular_particles/export_dialog.gd")
var checks := 0
var failures := 0
func check(value: bool, message: String) -> void:
	checks += 1
	if not value:
		failures += 1
		print("FAIL: ",message)
func _ready() -> void: run.call_deferred()
func choose_file(_mode, _filter) -> String: return ""
func snapshot(path: String, prefix: String = "") -> Dictionary:
	var result := {}
	var directory := DirAccess.open(path.path_join(prefix))
	for name in directory.get_files(): result[prefix.path_join(name)] = FileAccess.get_sha256(path.path_join(prefix).path_join(name))
	for name in directory.get_directories(): result.merge(snapshot(path,prefix.path_join(name)))
	return result
func run() -> void:
	var doc := Fixtures.basic()
	doc.emitter = {"rate":0.0,"duration":2.0,"loop":true,"bursts":[{"time":0.0,"count":128}],"lifetime":1.5}
	doc.modules.initialize.inputs[0].default = 0.0
	doc.renderer.quad_size = 0.4
	var original := doc.duplicate(true)
	var dialog := Dialog.new()
	add_child(dialog)
	dialog.setup(self)
	check(dialog.values() == {"render_target":"3d"},"UI default remains 3D")
	dialog.target.select(1)
	dialog.target.item_selected.emit(1)
	check(dialog.settings.visible and dialog.values().pixels_per_unit == 100.0 and dialog.values().flip_y,"2D defaults")
	var compiled := Compiler.new().compile(doc)
	check(compiled.errors.is_empty(),"shared compilation")
	var root := ProjectSettings.globalize_path("res://standalone-2d")
	var sprite_path := ProjectSettings.globalize_path("res://export-sprite.png")
	var image := Image.create(4,4,false,Image.FORMAT_RGBA8)
	image.fill(Color.RED)
	check(image.save_png(sprite_path) == OK,"test PNG")
	dialog.sprite.text = sprite_path
	dialog.blend.select(1)
	var options := dialog.values()
	var exporter := Exporter.new()
	var exported := await exporter.export_bundle(compiled.effect,root,128,"",options)
	check(exported.error.is_empty(),"2D export: "+exported.error)
	if exported.error.is_empty():
		check(exported.manifest.render_target == "2d" and exported.manifest.effect_version == 3,"manifest target and version")
		for relative in exported.manifest.files:
			check(FileAccess.get_sha256(root.path_join(relative)) == exported.manifest.files[relative],"checksum: "+relative)
		var packed: MMParticleEffect = load(root.path_join("effects/modular_particles/effect.res"))
		check(packed.shader_file != null and packed.source_hash == compiled.effect.source_hash,"common precompiled shader")
		var sprite: Texture2D = load(root.path_join("effects/modular_particles/sprite.res"))
		check(sprite.get_image().get_pixel(0,0) == Color.RED,"image pixels embedded")
		var scene := FileAccess.get_file_as_string(root.path_join("effects/modular_particles/particles.tscn"))
		check(scene.contains("particles_2d.gd") and not scene.contains(sprite_path),"portable node and texture paths")
		check(FileAccess.get_file_as_string(root.path_join("effects/modular_particles/demo.tscn")).contains("Camera2D"),"2D demo")
		var before := snapshot(root)
		var repeated := await exporter.export_bundle(compiled.effect,root,128,"",options)
		check(repeated.error.is_empty(),"repeat owned 2D export")
		before = snapshot(root)
		var bad := await exporter.export_bundle(compiled.effect,root,128)
		check(not bad.error.is_empty() and before == snapshot(root),"target switch cannot overwrite")
		for invalid in [{"render_target":"2d","pixels_per_unit":0},{"render_target":"3d","flip_y":true},{"render_target":"2d","sprite":sprite_path+"missing.png"}]:
			bad = await exporter.export_bundle(compiled.effect,root,128,"",invalid)
			check(not bad.error.is_empty() and before == snapshot(root),"invalid options preserve output")
		var managed := root.path_join("effects/modular_particles/sprite.res")
		var pristine := FileAccess.get_file_as_bytes(managed)
		Exporter._write(managed,pristine + PackedByteArray([0]))
		before = snapshot(root)
		bad = await exporter.export_bundle(compiled.effect,root,128,"",options)
		check(not bad.error.is_empty() and before == snapshot(root),"modified sprite protected")
		Exporter._write(managed,pristine)
		# This input was generated by this test, not a user-owned asset.
		DirAccess.remove_absolute(sprite_path)
		check(sprite.get_image().get_pixel(0,0) == Color.RED,"source PNG no longer required")
	check(doc == original,"UI/export never modifies authoring document")
	dialog.queue_free()
	print("MODULAR_EXPORT_2D ","PASS" if failures == 0 else "FAIL"," checks=",checks," bundle=",root)
	await mm_renderer.stop_rendering_thread()
	get_tree().quit(0 if failures == 0 else 1)
