extends "test_unified.gd"

func run():
	DirAccess.make_dir_recursive_absolute("res://exported")
	var graph = await make_graph()
	for type in MMGenParticle.Interface.TYPES:
		var node = await particle(graph, "Parameter", {"kind": "uniform", "data_type": type, "uniform": "test_value"})
		check(node.get_type_name() == "Typed Parameter", "Parameter title: " + type)
		check(node.option_values("data_type").has(type), "Parameter supports " + type)
		if not type.begins_with("sampler"):
			var key := "v0_0" if type.begins_with("mat") else ("v0" if "vec" in type else "value")
			check(not node.get_parameter_def(key).is_empty(), "Typed default control: " + type)
			if not node.get_parameter_def(key).is_empty():
				var value = true if type == "bool" or type.begins_with("bvec") else 2
				node.set_parameter(key, value)
				var restored = await add(graph, JSON.parse_string(JSON.stringify(node.serialize())))
				check(restored.uniform_definition().value == node.uniform_definition().value, "Typed default roundtrip: " + type)
				check(restored.get_parameter(key) == value, "Typed component roundtrip: " + type)
				restored.free()
		else:
			check(not node.get_parameter_def("resource").is_empty() and node.get_parameter_def("default_json").is_empty(), "Sampler resource UI")
		node.set_parameter("is_array", true)
		node.set_parameter("array_size", 2)
		if type.begins_with("sampler"):
			var paths: Array = node.uniform_definition().resources
			check(paths.is_empty() or paths.size() == 2, "Empty sampler arrays keep valid resource defaults")
		check(not node.get_parameter_def("resources" if type.begins_with("sampler") else "default_json").is_empty(), "Array controls: " + type)
		node.set_parameter("is_array", false)
		node.free()
	var legacy = await add(graph, {"type": "particle_node", "name": "LegacyArray", "settings": {"kind": "uniform", "data_type": "float", "uniform": "weights"}, "parameters": {"array_size": 3, "default_json": "[1,2,3]"}})
	check(legacy.get_parameter("is_array") and legacy.uniform_definition().array_size == 3, "Legacy arrays infer array mode")
	legacy.set_parameter("is_array", false)
	check(legacy.uniform_definition().value == 1.0, "First scalar toggle uses first element")
	var scalar_copy = await add(graph, JSON.parse_string(JSON.stringify(legacy.serialize())))
	check(not scalar_copy.get_parameter("is_array") and scalar_copy.uniform_definition().array_size == 0 and scalar_copy.get_parameter("array_size") == 3, "Inactive size survives save without making a scalar an array")
	scalar_copy.free()
	legacy.set_parameter("is_array", true)
	check(legacy.uniform_definition().value == [1.0, 2.0, 3.0], "Legacy array defaults restored")
	var element = await particle(graph, "Element", {"kind": "array_get", "data_type": "float", "array_size": 3})
	graph.connect_children(legacy, 0, element, 0)
	connect_output(graph, element, "Process", "MASS")
	var array_export = await preload("res://addons/material_maker/particles/graph_exporter.gd").export_graph(graph, "res://exported/parameter_array")
	check(array_export.errors.is_empty(), "Migrated array exports")
	var array_material = load("res://exported/parameter_array.tres")
	check(array_material.get_shader_parameter("weights") == PackedFloat32Array([1,2,3]), "Array defaults load from exported material")
	array_export.mm_uniforms.weights = MMGenBase.ShaderUniform.new("weights", "float", array_material.get_shader_parameter("weights"), 3)
	array_export.code = array_export.code.insert(array_export.code.rfind("}"), "COLOR = abs(MASS - 1.0) < 0.0001 ? vec4(0,1,0,1) : vec4(1,0,0,1);\n")
	await render_probe({}, false, "parameter_array_element", false, array_export)
	graph.remove_generator(element)
	graph.remove_generator(legacy)
	var parameter = await add(graph, {"type": "particle_node", "name": "Velocity", "settings": {"kind": "uniform", "data_type": "vec3", "uniform": "velocity"}, "parameters": {"default_json": "[-1, 2, 3]"}})
	var math = await add(graph, {"type": "math_v3", "name": "Math"})
	graph.connect_children(parameter, 0, math, 0)
	connect_output(graph, math, "Material", "CUSTOM")
	connect_output(graph, math, "Process", "USERDATA1")
	var result = await preload("res://addons/material_maker/particles/graph_exporter.gd").export_graph(graph, "res://exported/parameter")
	check(result.errors.is_empty(), "Parameter graph exports: " + str(result.errors))
	var shader := Shader.new()
	shader.code = result.code
	check(shader.get_shader_uniform_list().map(func(u): return u.name) == ["velocity"], "One public parameter across stages")
	result.code = result.code.insert(result.code.rfind("}"), "COLOR = all(lessThan(abs(CUSTOM.xyz - vec3(4.0, 5.0, 6.0)), vec3(0.0001))) && all(lessThan(abs(USERDATA1.xyz - CUSTOM.xyz), vec3(0.0001))) ? vec4(0.0, 1.0, 0.0, 1.0) : vec4(1.0, 0.0, 0.0, 1.0);\n")
	result.mm_uniforms.velocity = MMGenBase.ShaderUniform.new("velocity", "vec3", Vector3(4, 5, 6))
	await render_probe({}, false, "parameter_override", false, result)
	parameter.set_parameter("uniform_name", "uniform")
	var invalid = Exporter.validate(graph.get_node("Material").compile_shader())
	check(not invalid.errors.is_empty() and invalid.errors.any(func(e): return str(e.node).contains("Velocity")), "Invalid name is localized to the parameter")
	parameter.set_parameter("uniform_name", "velocity")
	var duplicate = await add(graph, parameter.serialize())
	connect_output(graph, duplicate, "Process", "MASS")
	check(graph.get_node("Material").compile_shader().errors.is_empty(), "Matching definitions share one parameter")
	duplicate.set_parameter("default_json", "[9, 8, 7]")
	invalid = graph.get_node("Material").compile_shader()
	check(not invalid.errors.is_empty() and invalid.errors.any(func(e): return not str(e.node).is_empty()), "Conflicting definitions identify a node")
	duplicate.set_parameter("default_json", "[-1, 2, 3]")
	var group = graph.create_subgraph([parameter, math])
	graph.create_subgraph([group])
	var restored = await mm_loader.create_gen(JSON.parse_string(JSON.stringify(graph.serialize())))
	add_child(restored)
	check(Exporter.validate(restored.get_node("Material").compile_shader()).errors.is_empty(), "Nested parameter graph roundtrip")
	restored.queue_free()
	parameter.set_parameter("default_json", "invalid")
	check(not graph.get_node("Material").compile_shader().errors.is_empty(), "Invalid default rejected")
	parameter.set_parameter("default_json", "[-1, 2, 3]")
	var buffer = await add(graph, {"type": "buffer", "name": "ParameterBuffer", "version": 2, "parameters": {"size": 4}})
	graph.connect_children(duplicate, 0, buffer, 0)
	connect_output(graph, buffer, "Process", "COLOR")
	check(str(graph.get_node("Material").compile_shader().errors).contains("cannot bake"), "External parameters cannot enter a static bake")
	graph.queue_free()
	for frame in 5: await get_tree().process_frame
	await mm_renderer.stop_rendering_thread()
	print("PARTICLE_PARAMETERS: failures=" + str(failures))
	get_tree().quit(0 if failures.is_empty() else 1)
