extends "test_unified.gd"

func uv_node(graph, name: String, value: Array):
	return await particle(graph, name, {"kind": "constant", "data_type": "vec2", "value": value})

func run():
	DirAccess.make_dir_recursive_absolute("res://exported")
	var graph = await make_graph()
	for name in ["Material", "Process"]:
		var ports = graph.get_node(name).get_input_defs()
		check(ports[-1].name == "sampling_uv", "Sampling UV appended to " + name)
	if not failures.is_empty():
		print("PARTICLE_SAMPLING: " + str(failures))
		get_tree().quit(1)
		return
	var source = await add(graph, {"type": "shader", "name": "UV", "shader_model": {"name": "UV Probe", "parameters": [], "inputs": [], "outputs": [{"type": "rgb", "rgb": "vec3($uv, 0.5)"}]}})
	var multiply = await particle(graph, "Multiply", {"kind": "operator", "data_type": "vec3", "operation": "multiply", "inputs": {"b": {"value": [2.0, 2.0, 2.0]}}})
	graph.connect_children(source, 0, multiply, 0)
	connect_output(graph, multiply, "Material", "CUSTOM")
	connect_output(graph, multiply, "Process", "USERDATA1")
	await probe(graph, "all(lessThan(abs(CUSTOM - vec4(0.0, 0.0, 1.0, 1.0)), vec4(0.00001))) && all(lessThan(abs(USERDATA1 - CUSTOM), vec4(0.00001)))", "sampling_default")
	var start_uv = await uv_node(graph, "StartUV", [0.2, 0.3])
	var process_uv = await uv_node(graph, "ProcessUV", [0.6, 0.7])
	connect_output(graph, start_uv, "Material", "sampling_uv")
	connect_output(graph, process_uv, "Process", "sampling_uv")
	var expected := "all(lessThan(abs(CUSTOM - vec4(0.4, 0.6, 1.0, 1.0)), vec4(0.00001))) && all(lessThan(abs(USERDATA1 - vec4(1.2, 1.4, 1.0, 1.0)), vec4(0.00001)))"
	await probe(graph, expected, "sampling_stage_coordinates")
	var evaluate = await particle(graph, "Sample", {"kind": "evaluate", "function_type": "rgb"})
	var local_uv = await uv_node(graph, "LocalUV", [0.8, 0.9])
	graph.connect_children(multiply, 0, evaluate, 0)
	graph.connect_children(local_uv, 0, evaluate, 1)
	connect_output(graph, evaluate, "Process", "USERDATA2")
	expected += " && all(lessThan(abs(USERDATA2 - vec4(1.6, 1.8, 1.0, 1.0)), vec4(0.00001)))"
	await probe(graph, expected, "sampling_branch_override")
	var module = graph.create_subgraph([source, multiply])
	var nested = graph.create_subgraph([module])
	var lib = load("res://material_maker/tools/library_manager/library.gd").new()
	lib.create_library("res://app_sampling_library.json", "Sampling test")
	lib.add_item("Modules/Sampling", null, nested.serialize())
	lib.load_library("res://app_sampling_library.json")
	var reused = await add(graph, lib.get_item("Modules/Sampling").item)
	connect_output(graph, reused, "Process", "USERDATA1")
	lib.free()
	var restored = await mm_loader.create_gen(JSON.parse_string(JSON.stringify(graph.serialize())))
	add_child(restored)
	await probe(restored, expected, "sampling_subgraph_roundtrip")
	FileAccess.open("res://app_sampling.ptex", FileAccess.WRITE).store_string(JSON.stringify(restored.serialize(), "\t"))
	var exported = await preload("res://addons/material_maker/particles/graph_exporter.gd").export_graph(restored, "res://exported/sampling")
	check(exported.errors.is_empty(), "Sampling material export")
	check(load("res://exported/sampling.tres") is ShaderMaterial, "Sampling material reload")
	restored.queue_free()
	var noise_graph = await make_graph()
	var noise = await add(noise_graph, {"type": "noise", "name": "Noise"})
	var transform = await add(noise_graph, {"type": "transform", "name": "Transform", "parameters": {"translate_x": 0.1, "translate_y": 0.2}})
	noise_graph.connect_children(noise, 0, transform, 0)
	var noise_uv = await uv_node(noise_graph, "UV", [0.6, 0.7])
	connect_output(noise_graph, noise_uv, "Process", "sampling_uv")
	connect_output(noise_graph, transform, "Process", "USERDATA1")
	var reference = await particle(noise_graph, "Reference", {"kind": "evaluate", "function_type": "rgba"})
	var reference_uv = await uv_node(noise_graph, "ReferenceUV", [0.5, 0.5])
	noise_graph.connect_children(noise, 0, reference, 0)
	noise_graph.connect_children(reference_uv, 0, reference, 1)
	connect_output(noise_graph, reference, "Process", "USERDATA2")
	await probe(noise_graph, "all(lessThan(abs(USERDATA1 - USERDATA2), vec4(0.00001)))", "sampling_noise_transform")
	noise_graph.queue_free()
	var state_graph = await make_graph()
	var initial_mass = await particle(state_graph, "InitialMass", {"kind": "constant", "data_type": "float", "value": 0.2})
	connect_output(state_graph, initial_mass, "Material", "MASS")
	connect_output(state_graph, initial_mass, "Process", "MASS")
	var mass = await particle(state_graph, "ReadMass", {"kind": "input", "builtin": "MASS"})
	var mass_uv = await particle(state_graph, "MassUV", {"kind": "compose", "data_type": "vec2", "inputs": {"c1": {"value": 0.3}}})
	state_graph.connect_children(mass, 0, mass_uv, 0)
	connect_output(state_graph, mass_uv, "Process", "sampling_uv")
	var uv_color = await add(state_graph, {"type": "shader", "shader_model": {"name": "UV", "parameters": [], "inputs": [], "outputs": [{"type": "rgb", "rgb": "vec3($uv, 0.5)"}]}})
	connect_output(state_graph, uv_color, "Process", "USERDATA1")
	var mass_math = await add(state_graph, {"type": "math_v3", "name": "MassMath", "parameters": {"op": 0, "d_in2_x": 1.0, "d_in2_y": 2.0, "d_in2_z": 3.0}})
	state_graph.connect_children(mass, 0, mass_math, 0)
	connect_output(state_graph, mass_math, "Process", "USERDATA2")
	var entry = await particle(state_graph, "Entry", {"kind": "entry", "stage": "process"})
	var before_write = await particle(state_graph, "BeforeWrite", {"kind": "set", "builtin": "CUSTOM"})
	var write_mass = await particle(state_graph, "WriteMass", {"kind": "set", "builtin": "MASS", "inputs": {"value": {"value": 0.8}}})
	state_graph.connect_children(entry, 0, before_write, 0)
	state_graph.connect_children(mass_math, 0, before_write, 2)
	state_graph.connect_children(before_write, 0, write_mass, 0)
	connect_output(state_graph, write_mass, "Process", "exec")
	await probe(state_graph, "all(lessThan(abs(USERDATA1 - vec4(entry_mass, 0.3, 0.5, 1.0)), vec4(0.00001))) && all(lessThan(abs(CUSTOM - vec4(vec3(entry_mass) + vec3(1.0, 2.0, 3.0), 1.0)), vec4(0.00001))) && all(lessThan(abs(USERDATA2 - vec4(1.8, 2.8, 3.8, 1.0)), vec4(0.00001))) && abs(MASS - 0.2) < 0.00001", "sampling_entry_snapshot_and_writes", "float entry_mass = MASS;\n")
	var emit = await particle(state_graph, "Emit", {"kind": "emit"})
	state_graph.connect_children(write_mass, 0, emit, 0)
	connect_output(state_graph, emit, "Process", "exec")
	var cast = await particle(state_graph, "Cast", {"kind": "convert", "source_type": "bool", "data_type": "vec2"})
	state_graph.connect_children(emit, 1, cast, 0)
	connect_output(state_graph, cast, "Process", "sampling_uv")
	check(str(state_graph.get_node("Material").compile_shader().errors).contains("after its execution"), "Sampling UV rejects not-yet-executed Emit result")
	state_graph.queue_free()
	var invalid = await particle(graph, "InvalidUV", {"kind": "constant", "data_type": "vec3"})
	connect_output(graph, invalid, "Process", "sampling_uv")
	check(not graph.get_node("Material").compile_shader().errors.is_empty(), "Invalid UV type rejected")
	graph.queue_free()
	for frame in 30: await get_tree().process_frame
	await mm_renderer.stop_rendering_thread()
	print("PARTICLE_SAMPLING: failures=" + str(failures))
	get_tree().quit(0 if failures.is_empty() else 1)
